import type { NextPage } from 'next'
import Head from 'next/head'
import Heroe from '../components/Heroe'
import Navbar from '../components/Navbar'


const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <Heroe />
      

    </div>
  )
}

export default Home
