import type { NextPage } from 'next'
import Head from 'next/head'


const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      Product
      Features
      Pricing
      Login

      New
      Monograph Dashboard

      Powerful insights into your team
      Project planning and time tracking for agile teams

      Schedule a demo
      to see a live preview

    </div>
  )
}

export default Home
